# Generated by Django 3.1.7 on 2021-03-28 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Library',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(max_length=100, verbose_name='Ten thu vien')),
                ('store_addr', models.CharField(max_length=100, verbose_name='Dia chi')),
            ],
            options={
                'db_table': 'Library',
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=100, verbose_name='Ten sach')),
                ('book_price', models.CharField(max_length=100, verbose_name='Gia sach')),
                ('book_actor', models.CharField(max_length=100, verbose_name='Nha xuat ban')),
                ('store', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='myapp.library')),
            ],
            options={
                'db_table': 'Book',
            },
        ),
    ]
